spring.application.name=JobTracker
spring.datasource.url=jdbc:postgresql://localhost:5432/jira_lite
spring.datasource.username=postgres
spring.datasource.password=frostbjorne
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true